config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Le programme redirige la page d'accueil vers la page qui indique tous les événements (méthode 'index' du controller 'events_controller')
  root 'events#index'

  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

	# Une participation concerne forcément un unique participant
	# belongs_to :user # user au singulier car ne concerne qu'un seul utilisateur
  # -> cette ligne est remplacée par les 2 suivantes
  # pour avoir des administrateurs et des participants
  # (tous les 2 de la classe 'users') plutôt qu'uniquement
  # des users.

  # Une participation concerne forcément un unique administrateur (qui est de la classe 'User')
  belongs_to :administrator, class_name: "User"

  # Une participation concerne forcément un unique participant (qui est de la classe 'User')
  belongs_to :attendant, class_name: "User"

	# Une participation ne peut concerner qu'un unique événement
	belongs_to :event # event au singulier car une participation ne concerne qu'un seul événement




end

app/models/event.rb
class Event < ApplicationRecord

	# Un événement peut avoir plusieurs participations
	has_many :attendancies
	# Un événement peut avoir plusieurs utilisateurs via les participations
	#has_many :users, through: :attendancies # Les 2 au pluriel!
  
  # Un événement peut avoir plusieurs participants (qui sont de la classe 'User') via les participations
  has_many :attendants, through: :attendancies, foreign_key: 'attendant_id', class_name: "User"

  # Un événement appartient à un unique administrateur qui est de la classe 'User'
  belongs_to :administrator, foreign_key: 'administrator_id', class_name: "User"


  # ----------------------------------------
	# Validations
  
  # Méthode qui regarde si la date de l'événement n'est pas dans le passé
  def is_past?
  	errors.add(:start_date, message: "La date de l'événement ne doit pas être passée !") if start_date < Time.now
  end

  #def is_multiple_of_5(duration)
  #  if duration % 5 == 0
  #  end
  #end

  # Méthode qui affiche un message d'erreur si la durée de l'événement n'est pas un multiple de 5
  def is_multiple_of_5?
  	errors.add(:duration, message: "La durée doit être un multiple de 5.") unless
  	self.duration % 5 == 0
  end


  # La présence de la date de départ, de la durée, du titre, de la description, du prix et du lieu est obligatoire
  validates :start_date, :duration, :title, :description, :price, :location, presence: true
  

  #validates : date: {after: Time.now}
  
  # La durée en min doit obligatoirement être un multiple de 5
  # -> on fait appel à la méthode 'is_multiple_of_5' (/!\ ne pas oublier le '?')
  # et doit obligatoirement être > 0.
  validates :duration, numericality: {greater_than: 0}
  # /!\ si on fait appel à une méthode (ici 'is_multiple_of_5?')
  # on doit écrire 'validate', SANS le 's'
  validate :is_multiple_of_5? # Pas besoin d'écrire que ça concerne 'duration', on l'a déjà mis dans la méthode 'is_multiple_of_5?'
  
  # Le titre doit faire au minimum 5 caractères et au maximum 140
  # Si ce n'est pas le cas, un message d'erreur est affiché
  validates :title, length: { in: 5..140, too_short: 'Le titre est trop court.', too_long: 'Le titre est trop long.' }
  
  # La description doit faire au min 20 caractères et au max 1000
  # Sinon, un message d'erreur apparaît
  validates :description, length: { in: 20..1000, too_short: 'La description est trop courte.', too_long: 'La description est trop longue.' }
  
  # Le prix doit être compris entre 1 et 1000
  validates :price, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	# Un utilsateur peut participer à plusieurs événements via les participations
	# Un utilisateur peut être administrateur ou participant
	has_many :attendancies, foreign_key: 'attendant_id', class_name: "Attendance"
  has_many :events, through: :attendancies, foreign_key: 'administrator_id', class_name: "Event"
  
  # has_many :attendancies
  # has_many :events, through: :attendancies
  
  # Après la création d'un nouvel user, il doit y avoir un envoi de mail à celui-ci
  after_create :welcome_send

  # Méthode qui appelle le mailer 'AttendantMailer' et lui fait exécuter la méthode 'welcome_email' avec comme entrée l'instance créée (d'où le 'self')
  def welcome_send
  	AttendantMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # Méthode qui va permettre d'afficher tous les événements en redirigeant vers la page d'URL '/'
	def index
		# On récupère tous les événements dans la variable @events_array pour l'utiliser dans la view 'index.html.erb'
		@events_array = Event.all

	end

  # Méthode qui va permettre d'afficher la page pour pouvoir créer un nouvel événement en redirigeant vers la page d'URL '/event/new'
	def new

	end

  # Méthode qui va servir à afficher un événement en particulier en redirigeant vers la page d'URL '/event/id'
	def show
    @event = Event.find(params[:id])
	end

  # Méthode qui va créer le nouvel événement à partir du formulaire de 'new.html.erb' soumis par l'utilisateur
  # Le contenu de ce formulaire est accessible via le hash 'params'
  # A la création, l'utilisateur est redirigé vers la page 'show' de l'événement
  def create

  	@event = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], administrator_id: current_user.id)

    # Si l'événement a pu être sauvegardé dans la BDD, i.e. si @event.save est true
  	if @event.save
      flash[:success] = "Ton Evenement a été créé !"
      redirect_to events_path
    # Sinon
    else
      flash.now[:danger] = "Ton evenement n'a pas été créé"
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div  class="jumbotron jumbotron-fluid" style="height:32em;">
  <div class="container">
    <!-- <h1 class="display-4" style="text-align:center; padding-top:80px; color:white;">Hello les MOUSS'</h1> -->
    <h1 class="ml11" style="text-align:center; color:white; font-size:68px; padding-top:80px;">
      <span class="text-wrapper">
        <span class="line line1"></span>
        <span class="letters">Bienvenue sur EventBrite !</span>
      </span>
    </h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

    <p style="text-align:center; font-size:28px; padding-top:40px; padding-bottom:40px; color:white;" class="lead"><strong>Tu pourras trouver ici tous les évènements qui auront lieu dans ta région.</strong></p>

  </div>
</div>



<h1>Liste des événements</h1>

<% @events_array.each_with_index do |event, i| %>
<p>Evénement n°<%= i + 1 %> : <%= event.title %></p>
<p>Date de l'événement : <%= event.start_date %></p>
<p>Durée de l'événement : <%= event.duration %> min</p>
<p>Prix : <%= event.price %></p>
<p>Organisateur de l'événement : <%= event.administrator.first_name %> <%= event.administrator.last_name %></p>
<p></p>
<button type="button" class="btn btn-default"><a href="<%= event_path(event.id) %>">Voir l'événement</a></button>
</br>
<br/><br/>
<% end %>




<style>
.jumbotron {
   background-image: url("app/assets/images/slide_presta_event.jpg");
    background-repeat: no-repeat;
    background-size:cover;
    background-attachment:fixed;
    height:30em;
  }
</style>

app/views/events/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail_password] %> 
    <div class="alert alert-danger" role="alert">
      Mauvais mot de passe
    </div>
  <% end %>
</div>

<div class="contener text-center" style="margin: 10px">
  <% if flash[:fail] %> 
    <div class="alert alert-danger" role="alert">
      Une erreur s'est produite, veuillez réessayer!
    </div>
  <% end %>
</div>

<div class="container">
	<h4 class="card-title mt-3 text-center">Créer un événement</h4>
<hr>


<%= form_tag "/users", method: "post" do %>

	<div class="card bg-light">
	<article class="card-body mx-auto" style="max-width: 400px;">

		<form>
		<div class="form-group input-group">
			<div class="input-group-prepend">
			    <span class="input-group-text"> <i class="fas fa-table"></i> </span>
			 </div>
	        <input name="start_date" class="form-control" placeholder="Date de l'événement" type="text">
	    </div> 
	    <div class="form-group input-group">
			<div class="input-group-prepend">
			    <span class="input-group-text"> <i class="fas fa-hourglass-start"></i> </span>
			 </div>
	        <input name="duration" class="form-control" placeholder="Durée" type="text">
	    </div>

	    <div class="form-group input-group">
			<div class="input-group-prepend">
			    <span class="input-group-text"> <i class="fas fa-heading"></i> </span>
			 </div>
	        <input name="title" class="form-control" placeholder="Titre" type="text">
	    </div>
	    <div class="form-group input-group">
			<input name="description" class="form-control" placeholder="Décrivez l'événement" type="text">
	    </div>

	    <!-- form-group// -->
	    <div class="form-group input-group">
	    	<div class="input-group-prepend">
			    <span class="input-group-text"> <i class="fas fa-money-bill-alt"></i> </span>
			</div>
			<input name="price" class="form-control" placeholder="Prix" type="number">
	    </div>
	    
	    <!-- form-group// -->
	    <div class="form-group input-group">
	    	<div class="input-group-prepend">
			    <span class="input-group-text"> <i class="fas fa-location-arrow"></i> </span>
			</div>
			<input name="location" class="form-control" placeholder="Lieu" type="text">
	    </div>
			<!--
			<select name="city" class="form-control">
				<option selected="Montpellier, Ouagadougou"> Sélectionner un lieu</option>
			-->
				
			</select>
		</div> <!-- form-group end.// -->
	    
	    <div class="form-group input-group">
	    	
	        
	    </div> <!-- form-group// -->                                      
	    <div class="form-group">
	        <input type="submit" value="Créer l'événement" class="btn btn-primary btn-block"/>
	    </div> <!-- form-group// -->      
                                                                
	</form>
	</article>
	</div> <!-- card.// -->
	</div>
	</div>
<% end %>
<!--container end.//-->

app/views/events/show.html.erb
<h1>Page de l'événement</h1></div>

<p>Nom de l'événement : <%= @event.title %></p>
<p>Date de l'événement : <%= @event.start_date %></p>
<p>Durée de l'événement : <%= @event.duration %> min</p>
<p>Prix : <%= @event.price %></p>
<p>Organisateur de l'événement : <%= @event.administrator.first_name %> <%= @event.administrator.last_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Lien CSS Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Liens JavaScript Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>
    <header>
      <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<header>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="<%=root_path %>">EventBrite</a>
      <!-- <%= link_to "Eventbrite", root_path %> -->
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%=new_event_path %>">Créer un événement</a>
      <!-- <%= link_to "Créer un événement", new_event_path %> -->
    </li>
    <li class="nav-item">
      <!--<a class="nav-link" href="#">Link</a>-->

    <!-- Si l'utilisateur n'est pas connecté -->
    <% if !user_signed_in? %>
      <!-- Bouton dropdown avec 'Inscription/Connextion' si l'utilisateur n'est pas connecté -->
      <div class="dropdown">
      <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown">S'inscrire/Se connecter
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        
        <li><a href="<%=new_user_registration_path %>">Inscription</a></li>
        <li><a href="<%=new_user_session_path %>">Connection</a></li>
    
    <!-- Si l'utilisateur est connecté (i.e. si '!user_signed_in?' est false) -->
    <%else %>
      <!-- Bouton 'Mon profil' -->
      <div class="dropdown">
      <button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown">Mon profil
      <span class="caret"></span></button>
      <ul class="dropdown-menu">
        
        <li><a href="<%=user_session_path %>">Mon profil</a></li>
        <li><a href="<%=destroy_user_session_path %>">Se déconnecter</a></li>

    <% end %>
     
    </ul>
  </div>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Disabled</a>
    </li>
  </ul>
</nav>
</header>

  <body>

    <%= yield %>
  </body>
</html>